import Head from "next/head";
import Collection from "../components/Collection";
import Discover from "../components/Discover";
import MoreNfts from "../components/morenfts";
import SellNfts from "../components/SellNfts";
import TopCollections from "../components/TopCollections";
import Transaction from "../components/Transaction";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nfters</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Discover />
        <Transaction />
        <TopCollections />
        <Collection />
        <SellNfts />
        <MoreNfts />
      </main>
    </div>
  );
}
