import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nfters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-200 h-screen">
        <h1 className="text-3xl font-bold">main Section</h1>
      </main>
    </div>
  );
}
